/**
 * When a driver must report a car crash, and to whom — all 50 states + D.C.
 *
 * Every entry was checked on 2026-09-29 against an official source: the
 * state DMV / public-safety / transportation agency, or the state's own
 * published statute. `sourceUrl` is that source. Nothing here comes from a
 * secondary law-firm list; several of those are out of date (Minnesota
 * repealed its driver report in 2021, Texas discontinued the CR-2 in 2017,
 * Delaware raised its threshold to $2,000, Nebraska to $2,000 for crashes
 * on or after July 18, 2026).
 *
 * Where the official text could not be confirmed, `kind` is "unconfirmed"
 * and the page says so instead of guessing. Fields are null when the
 * source did not state them — never filled in from memory.
 *
 * `kind` values:
 *   driver-report           You must file your own written report, even if police came.
 *   driver-report-if-no-police  You file only when police did not investigate/report it.
 *   police-notice           You must notify police; police write the report. No driver form.
 *   no-driver-form          The state accepts no driver-filed report; police report only.
 *   uninsured-only          A driver report is required only when an uninsured driver is involved.
 *   optional                Filing your own report is available but not required.
 *   on-request              The state may require a report after it asks you for one.
 *   unconfirmed             We could not confirm the current rule from an official source.
 */

export type ReportKind =
  | "driver-report"
  | "driver-report-if-no-police"
  | "police-notice"
  | "no-driver-form"
  | "uninsured-only"
  | "optional"
  | "on-request"
  | "unconfirmed";

export interface StateCrashReporting {
  state: string;
  kind: ReportKind;
  /** Plain-English trigger: what kind of crash requires action. */
  trigger: string;
  /** Who you report to (agency), or null if not stated. */
  reportTo: string | null;
  /** Deadline as stated by the source, or null. */
  deadline: string | null;
  /** Official form name/number, or null. */
  formName: string | null;
  /** Extra state-specific detail worth knowing. */
  note?: string;
  sourceUrl: string;
  sourceLabel: string;
}

export const CRASH_REPORTING_CHECKED = "2026-09-29";

export const STATE_CRASH_REPORTING: StateCrashReporting[] = [
  {
    state: "Alabama",
    kind: "uninsured-only",
    trigger: "A crash caused by an uninsured motorist that results in death, injury, or more than $500 of damage to any one owner's property.",
    reportTo: "Alabama Law Enforcement Agency (ALEA), Driver License Division",
    deadline: null,
    formName: "SR-31",
    note: "ALEA says the SR-31 is required only for crashes involving an uninsured motorist. Police crash reports can be bought online or at any ALEA Driver License office.",
    sourceUrl: "https://www.alea.gov/dps/driver-license/driver-records-crash-reports-and-driver-license-reinstatements",
    sourceLabel: "ALEA — Driver Records, Crash Reports, and Reinstatements",
  },
  {
    state: "Alaska",
    kind: "driver-report",
    trigger: "Injury, death, or total property damage of $2,000 or more.",
    reportTo: "Alaska Division of Motor Vehicles (and the local police department if the crash was inside a municipality)",
    deadline: "Within 10 days",
    formName: "Alaska Motor Vehicle Crash Form 12-209",
    note: "The 12-209 can be submitted online. Alaska also uses it for smaller crashes ($501–$2,000) as proof of liability insurance.",
    sourceUrl: "https://dmv.alaska.gov/vehicle-services/vehicle-services/vehicle-services/report-a-crash/",
    sourceLabel: "Alaska DMV — Report a Crash",
  },
  {
    state: "Arizona",
    kind: "police-notice",
    trigger: "Any crash that injures or kills someone.",
    reportTo: "Local police, county sheriff, or the nearest highway patrol office",
    deadline: "Immediately",
    formName: null,
    note: "For a crash on private property where police did not come, ADOT MVD says you need a law-enforcement crash report before you can request the other driver's insurance information.",
    sourceUrl: "https://www.azleg.gov/ars/28/00666.htm",
    sourceLabel: "Arizona Revised Statutes § 28-666",
  },
  {
    state: "Arkansas",
    kind: "driver-report",
    trigger: "Injury, death, or more than $1,000 of damage to any one person's property — regardless of who was at fault.",
    reportTo: "Arkansas Department of Finance and Administration (DFA), Safety Responsibility",
    deadline: "Within 30 days",
    formName: "SR-1 Motor Vehicle Accident Report",
    sourceUrl: "https://www.dfa.arkansas.gov/office/driver-services/safety-responsibility-2/",
    sourceLabel: "Arkansas DFA — Safety Responsibility",
  },
  {
    state: "California",
    kind: "driver-report",
    trigger: "Anyone injured (however minor) or killed, or property damage over $1,000.",
    reportTo: "California DMV",
    deadline: "Within 10 days",
    formName: "SR-1, Report of Traffic Accident Occurring in California",
    note: "Required in addition to any police, CHP, or insurance report. You, your insurance agent, broker, or legal representative can file it, including online. DMV can suspend your license for not filing.",
    sourceUrl: "https://www.dmv.ca.gov/portal/dmv-virtual-office/accident-reporting/",
    sourceLabel: "California DMV — Accident Reporting (SR-1)",
  },
  {
    state: "Colorado",
    kind: "optional",
    trigger: "Police were not called to the scene.",
    reportTo: "Colorado Department of Revenue (online crash reporting system)",
    deadline: null,
    formName: "Online crash report (\"counter report\")",
    note: "A report you file online is not investigated by police and is kept for record purposes only. Copies can be released only with the filer's written consent (form DR 2559).",
    sourceUrl: "https://dmv.colorado.gov/report-accident",
    sourceLabel: "Colorado DMV — Report a Crash and Obtain a Crash Record",
  },
  {
    state: "Connecticut",
    kind: "unconfirmed",
    trigger: "Police must file a report for crashes with injury, death, or more than $1,000 of property damage.",
    reportTo: null,
    deadline: null,
    formName: null,
    note: "We could not confirm from Connecticut's official DMV pages whether drivers must also file their own report. Ask the investigating police department, or contact CT DMV.",
    sourceUrl: "https://portal.ct.gov/dmv/resources/dmv-forms",
    sourceLabel: "Connecticut DMV — Forms",
  },
  {
    state: "Delaware",
    kind: "police-notice",
    trigger: "Injury or death; property damage of $2,000 or more on a public highway; or a driver who appears impaired by alcohol or drugs.",
    reportTo: "Police",
    deadline: "Immediately",
    formName: null,
    note: "Delaware raised this threshold from $500 to $2,000. Police complete the State of Delaware Uniform Traffic Collision Report. A standard Delaware State Police collision report costs $25.",
    sourceUrl: "https://delcode.delaware.gov/title21/c042/index.html",
    sourceLabel: "Delaware Code, Title 21, Chapter 42",
  },
  {
    state: "Florida",
    kind: "driver-report-if-no-police",
    trigger: "Crashes with apparent damage of at least $500 are reportable. If law enforcement did not write a report and you are eligible, you can file your own.",
    reportTo: "Florida Department of Highway Safety and Motor Vehicles (FLHSMV)",
    deadline: null,
    formName: "Driver Report of Traffic Crash (Self Report), HSMV 90011S",
    note: "Complete and sign the form and email it to SelfReportCrashes@flhsmv.gov.",
    sourceUrl: "https://www.flhsmv.gov/traffic-crash-reports/",
    sourceLabel: "FLHSMV — Traffic Crash Reports",
  },
  {
    state: "Georgia",
    kind: "police-notice",
    trigger: "Injury, death, or property damage over $500.",
    reportTo: "The nearest law enforcement agency",
    deadline: "Immediately",
    formName: null,
    note: "You must also exchange names, addresses, plate numbers and driver's license numbers with the other driver.",
    sourceUrl: "https://dds.georgia.gov/section-11-crashes",
    sourceLabel: "Georgia DDS Driver's Manual — Section 11: Crashes",
  },
  {
    state: "Hawaii",
    kind: "driver-report",
    trigger: "Injury, death, or more than $3,000 of damage to any one person's property (including your own).",
    reportTo: "The chief of police, in writing or in person",
    deadline: "Within 24 hours",
    formName: null,
    sourceUrl: "https://www.capitol.hawaii.gov/hrscurrent/Vol05_Ch0261-0319/HRS0287/HRS_0287-0004.htm",
    sourceLabel: "Hawaii Revised Statutes § 287-4",
  },
  {
    state: "Idaho",
    kind: "police-notice",
    trigger: "Injury, death, or more than $1,500 of damage to any one person's property.",
    reportTo: "City police if inside a city; otherwise the county sheriff or nearest Idaho State Police office",
    deadline: "Immediately",
    formName: null,
    sourceUrl: "https://legislature.idaho.gov/statutesrules/idstat/title49/t49ch13/sect49-1305/",
    sourceLabel: "Idaho Code § 49-1305",
  },
  {
    state: "Illinois",
    kind: "driver-report-if-no-police",
    trigger: "Police did not come to the scene and damage is over $1,500 (all drivers insured) or over $500 (any driver uninsured), or anyone was injured.",
    reportTo: "Illinois State Police / IDOT (Illinois Motorist Report)",
    deadline: "Within 10 days",
    formName: "Illinois Motorist Report",
    sourceUrl: "https://idot.illinois.gov/form-and-reports/crash-reports.html",
    sourceLabel: "IDOT — Crash Reports",
  },
  {
    state: "Indiana",
    kind: "driver-report",
    trigger: "Injury, death, or total property damage of $1,000 or more.",
    reportTo: "Indiana Bureau of Motor Vehicles (BMV)",
    deadline: "Within 10 days",
    formName: "Indiana Operator's Proof of Insurance/Crash Report (SR21)",
    note: "Failure to report can lead to suspension of your license and registration.",
    sourceUrl: "https://www.in.gov/bmv/licenses-permits-ids/suspension-and-reinstatement/proof-of-financial-responsibility",
    sourceLabel: "Indiana BMV — Proof of Financial Responsibility",
  },
  {
    state: "Iowa",
    kind: "driver-report-if-no-police",
    trigger: "Injury, death, or total property damage of $1,500 or more, when no law enforcement agency investigated.",
    reportTo: "Iowa Department of Transportation",
    deadline: "Within 72 hours",
    formName: "Iowa Accident Report",
    note: "Iowa DOT says failing to return the form within 72 hours may result in suspension of your driving privileges.",
    sourceUrl: "https://iowadot.gov/drivers-licenses-ids/other-services/accident-reports",
    sourceLabel: "Iowa DOT — Accident Reports",
  },
  {
    state: "Kansas",
    kind: "police-notice",
    trigger: "Injury, death, or $1,000 or more in total damage.",
    reportTo: "Police",
    deadline: null,
    formName: null,
    note: "Below $1,000 with no injuries, KDOT says a police report isn't necessary — but you must still stop and exchange information.",
    sourceUrl: "https://www.ksdot.gov/travel/traveler-safety/what-to-do-in-case-of-a-crash",
    sourceLabel: "KDOT — What to Do in Case of a Crash",
  },
  {
    state: "Kentucky",
    kind: "driver-report-if-no-police",
    trigger: "Property damage over $500 and no law enforcement officer investigated.",
    reportTo: "Kentucky State Police",
    deadline: "Within 10 days",
    formName: "Commonwealth of Kentucky Civilian Traffic Collision Report",
    note: "Kentucky State Police has an online civilian collision reporting site. Do not file one if an officer investigated.",
    sourceUrl: "https://www.kentuckystatepolice.ky.gov/civilian-collision-reports",
    sourceLabel: "Kentucky State Police — Civilian Collision Reports",
  },
  {
    state: "Louisiana",
    kind: "police-notice",
    trigger: "Injury, death, or property damage over $500.",
    reportTo: "City police inside a city or town; otherwise the sheriff or nearest state police station",
    deadline: "Immediately",
    formName: null,
    sourceUrl: "https://legis.la.gov/legis/Law.aspx?d=88361",
    sourceLabel: "Louisiana Revised Statutes — crash notice law (legis.la.gov)",
  },
  {
    state: "Maine",
    kind: "police-notice",
    trigger: "Injury, death, or apparent property damage of $2,000 or more.",
    reportTo: "State police, the sheriff's office, or the municipal police department",
    deadline: "Immediately",
    formName: null,
    note: "Maine's Secretary of State can suspend your license and registration for not reporting.",
    sourceUrl: "https://legislature.maine.gov/statutes/29-a/title29-asec2251.html",
    sourceLabel: "Maine Revised Statutes, Title 29-A § 2251",
  },
  {
    state: "Maryland",
    kind: "driver-report-if-no-police",
    trigger: "Anyone injured or killed, and no police officer investigated and filed a report.",
    reportTo: "Maryland Motor Vehicle Administration (MVA)",
    deadline: "Within 15 days",
    formName: null,
    note: "You must also file evidence of liability insurance within 15 days.",
    sourceUrl: "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gtr&enactments=false&section=20-107",
    sourceLabel: "Maryland Transportation Article § 20-107",
  },
  {
    state: "Massachusetts",
    kind: "driver-report",
    trigger: "Injury, death, or more than $1,000 of damage to any one vehicle or other property.",
    reportTo: "The Registry of Motor Vehicles, with a copy to the local police department where the crash happened",
    deadline: "Within 5 days",
    formName: "Motor Vehicle Crash Operator Report",
    sourceUrl: "https://www.mass.gov/how-to/report-a-motor-vehicle-crash",
    sourceLabel: "Mass.gov — Report a motor vehicle crash",
  },
  {
    state: "Michigan",
    kind: "police-notice",
    trigger: "Injury, death, or apparent property damage totaling $1,000 or more.",
    reportTo: "The nearest police station or police officer",
    deadline: "Immediately",
    formName: null,
    note: "Police file the UD-10 crash report with Michigan State Police. Reported crashes appear on your driving record regardless of fault.",
    sourceUrl: "https://legislature.mi.gov/Laws/MCL?objectName=MCL-257-622",
    sourceLabel: "Michigan Compiled Laws § 257.622",
  },
  {
    state: "Minnesota",
    kind: "no-driver-form",
    trigger: "Minnesota no longer takes driver-filed crash reports.",
    reportTo: null,
    deadline: null,
    formName: null,
    note: "The driver-report requirement (Minn. Stat. § 169.09, subd. 7) was repealed effective July 1, 2021. You can still request a law-enforcement crash report from Driver and Vehicle Services with form PS2503.",
    sourceUrl: "https://dps.mn.gov/divisions/dvs/contact/driver-and-vehicle-records-requests/request-crash-report",
    sourceLabel: "Minnesota DPS — Request a crash report",
  },
  {
    state: "Mississippi",
    kind: "unconfirmed",
    trigger: "Mississippi law makes failing to report a crash involving injury, death, or property damage a misdemeanor.",
    reportTo: null,
    deadline: null,
    formName: null,
    note: "We could not confirm the current dollar threshold or any driver form from an official source. Call police at the scene; Mississippi Highway Patrol reports can be bought in person or online.",
    sourceUrl: "https://www.dps.ms.gov/crash-reports",
    sourceLabel: "Mississippi DPS — Crash Reports",
  },
  {
    state: "Missouri",
    kind: "uninsured-only",
    trigger: "A crash with an uninsured motorist that injures or kills anyone, or causes more than $500 of damage to any one person's property.",
    reportTo: "Missouri Department of Revenue",
    deadline: "Within 30 days",
    formName: "Form 1140, Motor Vehicle Accident Report",
    note: "An uninsured driver who doesn't submit the form faces a one-year license suspension.",
    sourceUrl: "https://dor.mo.gov/driver-license/insurance/accident-information.html",
    sourceLabel: "Missouri DOR — Accident Information",
  },
  {
    state: "Montana",
    kind: "driver-report-if-no-police",
    trigger: "Injury, death, or property damage of $1,000 or more. Notify police immediately; if no officer writes a report and damage exceeds $1,000, you must report in writing.",
    reportTo: "Police immediately; then the Montana Highway Patrol if no officer's report is written",
    deadline: "Written report within 10 days",
    formName: null,
    sourceUrl: "https://dojmt.gov/montana-highway-patrol/crash-records/",
    sourceLabel: "Montana DOJ — Crash Records",
  },
  {
    state: "Nebraska",
    kind: "driver-report-if-no-police",
    trigger: "Injury, death, or damage to any one vehicle or property of $2,000 or more (crashes on or after July 18, 2026; $1,500 before), when law enforcement did not investigate.",
    reportTo: "Nebraska Department of Transportation",
    deadline: "Within 10 days",
    formName: "Driver's Motor Vehicle Crash Report (online)",
    sourceUrl: "https://dot.nebraska.gov/safety/crash-reporting/",
    sourceLabel: "Nebraska DOT — Crash Reporting",
  },
  {
    state: "Nevada",
    kind: "driver-report-if-no-police",
    trigger: "Injury, death, or damage of $750 or more, when a police officer did not investigate.",
    reportTo: "Nevada DMV",
    deadline: "Within 10 days",
    formName: "SR-1, Report of Traffic Accident",
    note: "Attach a repair estimate or total-loss statement, a copy of the insurance in effect on the crash date, and a doctor's statement for each injured person in your vehicle.",
    sourceUrl: "https://dmv.nv.gov/pdfforms/sr1.pdf",
    sourceLabel: "Nevada DMV — Form SR-1",
  },
  {
    state: "New Hampshire",
    kind: "driver-report-if-no-police",
    trigger: "Injury, or combined damage over $1,000, when police did not investigate.",
    reportTo: "New Hampshire Division of Motor Vehicles",
    deadline: "Within 15 days",
    formName: "Operator's Report (DSMV 400)",
    sourceUrl: "https://www.dmv.nh.gov/tickets-accidents-or-restorations/accidents-reports",
    sourceLabel: "NH DMV — Accident Reports",
  },
  {
    state: "New Jersey",
    kind: "driver-report-if-no-police",
    trigger: "Injury, death, or more than $500 of damage to any one person's property. Notify police immediately; if a written report is still needed, file it.",
    reportTo: "Local, county or state police immediately; written report within 10 days",
    deadline: "Within 10 days (written report)",
    formName: "Self-Reporting Crash Form (NJDOT)",
    note: "Failing to report can suspend both your driving and registration privileges.",
    sourceUrl: "https://www.nj.gov/transportation/refdata/accident/selfreporting.shtm",
    sourceLabel: "NJDOT — Self-Reporting Crash Form",
  },
  {
    state: "New Mexico",
    kind: "unconfirmed",
    trigger: "Crashes with injury, death, or property damage of $500 or more are reportable in New Mexico's crash records.",
    reportTo: null,
    deadline: null,
    formName: null,
    note: "New Mexico statute (NMSA § 66-7-207) has required a written report within five days for crashes of $500 or more, but we could not confirm the current text from an official source. Check with MVD or the investigating agency.",
    sourceUrl: "https://www.mvd.newmexico.gov/resources/frequently-asked-questions/",
    sourceLabel: "New Mexico MVD — FAQ",
  },
  {
    state: "New York",
    kind: "driver-report",
    trigger: "Injury, death, or more than $1,000 of damage to the property of any one person.",
    reportTo: "New York DMV",
    deadline: "Within 10 days",
    formName: "MV-104, Report of Motor Vehicle Crash",
    note: "Failing to report within 10 days is a misdemeanor and can lead to suspension or revocation of your license and registration.",
    sourceUrl: "https://dmv.ny.gov/records/file-a-motorist-crash-accident-report",
    sourceLabel: "NY DMV — File a Motorist Crash (Accident) Report",
  },
  {
    state: "North Carolina",
    kind: "police-notice",
    trigger: "Injury, death, or property damage of $1,000 or more.",
    reportTo: "City police inside a city or town; otherwise the State Highway Patrol or sheriff",
    deadline: "Immediately",
    formName: null,
    sourceUrl: "https://www.ncleg.gov/enactedlegislation/statutes/pdf/bysection/chapter_20/gs_20-166.1.pdf",
    sourceLabel: "N.C. General Statutes § 20-166.1",
  },
  {
    state: "North Dakota",
    kind: "police-notice",
    trigger: "Injury, death, or property damage of $4,000 or more (combined).",
    reportTo: "Local police, county sheriff, or North Dakota Highway Patrol",
    deadline: null,
    formName: null,
    note: "The threshold rose to $4,000 on August 1, 2019. Crash reports cost $7.",
    sourceUrl: "https://www.statepatrol.nd.gov/node/179",
    sourceLabel: "ND Highway Patrol — Crash reporting threshold",
  },
  {
    state: "Ohio",
    kind: "uninsured-only",
    trigger: "A crash in Ohio with an uninsured driver causing more than $400 of damage (with an itemized estimate) or personal injury over $500.",
    reportTo: "Ohio Bureau of Motor Vehicles",
    deadline: null,
    formName: "BMV 3303, Uninsured Accident Report",
    note: "Police forward their own crash reports (form OH-1) for crashes with injury, death, or property damage over $1,000.",
    sourceUrl: "https://dam.assets.ohio.gov/image/upload/publicsafety.ohio.gov/bmv3303.pdf",
    sourceLabel: "Ohio BMV — Form BMV 3303",
  },
  {
    state: "Oklahoma",
    kind: "police-notice",
    trigger: "Any crash that injures or kills someone. Separately, if a crash with $300 or more of damage hasn't been settled within six months, a written report goes to the Department of Public Safety.",
    reportTo: "Local police, county sheriff, or the nearest Highway Patrol office",
    deadline: "Immediately (injury or death)",
    formName: "Oklahoma Motor Vehicle Collision Report (for the six-month written report)",
    sourceUrl: "https://www.oscn.net/applications/oscn/DeliverDocument.asp?CiteID=82251",
    sourceLabel: "Oklahoma Statutes, Title 47 § 10-107",
  },
  {
    state: "Oregon",
    kind: "driver-report",
    trigger: "Injury or death; more than $2,500 of damage to your vehicle, any vehicle, or other property; or any vehicle towed from the scene.",
    reportTo: "Oregon DMV",
    deadline: "Within 72 hours",
    formName: "Oregon Traffic Collision and Insurance Report",
    note: "File online through DMV2U (fastest) or on paper. DMV must suspend your driving privileges if you don't file when required.",
    sourceUrl: "https://www.oregon.gov/odot/dmv/pages/driverid/accidentreport.aspx",
    sourceLabel: "Oregon DMV — Collision Reporting and Responsibilities",
  },
  {
    state: "Pennsylvania",
    kind: "driver-report-if-no-police",
    trigger: "Police did not investigate, and someone was injured or killed or a vehicle had to be towed.",
    reportTo: "PennDOT, Bureau of Highway Safety and Traffic Engineering",
    deadline: "Within 5 days",
    formName: "AA-600, Driver's Accident Report",
    sourceUrl: "https://www.pa.gov/content/dam/copapwp-pagov/en/penndot/documents/public/pubsforms/forms/aa-600.pdf",
    sourceLabel: "PennDOT — Form AA-600",
  },
  {
    state: "Rhode Island",
    kind: "driver-report",
    trigger: "Injury, death, or more than $1,000 of damage to any one person's property (including your own).",
    reportTo: "Rhode Island Division of Motor Vehicles (and police immediately)",
    deadline: "Within 21 days",
    formName: null,
    sourceUrl: "https://dmv.ri.gov/node/1401",
    sourceLabel: "RI DMV — What to do after a collision",
  },
  {
    state: "South Carolina",
    kind: "driver-report-if-no-police",
    trigger: "Total property damage of $1,000 or more, or injury or death, when law enforcement did not investigate.",
    reportTo: "SCDMV, Financial Responsibility",
    deadline: "Within 15 days",
    formName: "FR-309, Traffic Collision Report",
    note: "If SCDMV doesn't receive it in 15 days, your registration and driving privileges can be suspended.",
    sourceUrl: "https://dmv.sc.gov/Vehicle-Owners/Collision-Reports",
    sourceLabel: "SCDMV — Collision Reports",
  },
  {
    state: "South Dakota",
    kind: "unconfirmed",
    trigger: "South Dakota law requires immediate notice to law enforcement for crashes above a property-damage threshold (SDCL 32-34-7).",
    reportTo: "Law enforcement",
    deadline: "Immediately",
    formName: null,
    note: "We could not confirm the current dollar threshold from the official statute text. Treat any injury crash, or any crash with significant damage, as reportable and call police.",
    sourceUrl: "https://sdlegislature.gov/Statutes/32-34-7",
    sourceLabel: "South Dakota Codified Laws § 32-34-7",
  },
  {
    state: "Tennessee",
    kind: "driver-report",
    trigger: "Injury, death, more than $1,500 of property damage, or more than $400 of damage to state or local government property.",
    reportTo: "Tennessee Department of Safety and Homeland Security",
    deadline: "Within 20 days",
    formName: "Owner Operator Report",
    note: "Failing to file can suspend your license and registration.",
    sourceUrl: "https://www.tn.gov/safety/driver-services/reinstatements-and-moving-violations/owner-operator-report.html",
    sourceLabel: "Tennessee Safety — Submit an Owner Operator Report",
  },
  {
    state: "Texas",
    kind: "no-driver-form",
    trigger: "Texas no longer accepts a driver-filed crash report.",
    reportTo: null,
    deadline: null,
    formName: null,
    note: "The Driver's Crash Report (CR-2, the \"blue form\") was discontinued in 2017. Crashes are reported by law enforcement on the CR-3. If police didn't come, keep your own records of the crash for your claim.",
    sourceUrl: "https://www.txdot.gov/data-maps/crash-reports-records.html",
    sourceLabel: "TxDOT — Crash Reports and Records",
  },
  {
    state: "Utah",
    kind: "on-request",
    trigger: "Injury, death, or total property damage of $2,500 or more makes a crash reportable.",
    reportTo: "Utah Department of Public Safety",
    deadline: "Within 10 days after DPS requests it",
    formName: null,
    sourceUrl: "https://le.utah.gov/xcode/Title41/Chapter6a/41-6a-S402.html",
    sourceLabel: "Utah Code § 41-6a-402",
  },
  {
    state: "Vermont",
    kind: "driver-report",
    trigger: "Anyone injured, or total damage to all property of $3,000 or more.",
    reportTo: "Vermont DMV (by email to DMV.DriverControl@Vermont.gov or by mail)",
    deadline: "Within 72 hours",
    formName: "Operator Crash Report",
    note: "You must also give DMV proof that liability insurance was in force at the time of the crash.",
    sourceUrl: "https://dmv.vermont.gov/enforcement-and-safety/laws/crashes",
    sourceLabel: "Vermont DMV — Crashes",
  },
  {
    state: "Virginia",
    kind: "police-notice",
    trigger: "Crashes are reported by law enforcement; Virginia DMV also accepts reports from a driver, owner or representative.",
    reportTo: "Police; Virginia DMV",
    deadline: null,
    formName: "FR200 accident report (with CRD-93 request form)",
    note: "Virginia DMV charges $8 for a copy of a crash report.",
    sourceUrl: "https://www.dmv.virginia.gov/vehicles/general/crash-dmv",
    sourceLabel: "Virginia DMV — Reporting a Crash to DMV",
  },
  {
    state: "Washington",
    kind: "driver-report-if-no-police",
    trigger: "Injury, or $1,000 or more of damage to any one vehicle or property, when an officer is not completing a police report.",
    reportTo: "Washington State Patrol, Collision Records Section",
    deadline: "Within 4 days",
    formName: "Motor Vehicle Collision Report (MVCR)",
    note: "File online through WSP's OMVCR system (you get a report number immediately), by mail, or by email.",
    sourceUrl: "https://wsp.wa.gov/driver/collision-records/",
    sourceLabel: "Washington State Patrol — Collision Reports",
  },
  {
    state: "Washington, D.C.",
    kind: "police-notice",
    trigger: "Injury, death, or a vehicle so damaged it has to be towed — MPD writes a Traffic Crash Report (PD-10).",
    reportTo: "Metropolitan Police Department (MPD)",
    deadline: null,
    formName: "Motor Vehicle Crash Report for Property Damage Only (for minor crashes)",
    note: "For minor crashes that don't need a full police report, MPD officers give drivers the District's Property Damage Only form.",
    sourceUrl: "https://mpdc.dc.gov/service/request-accident-report-pd-10-or-incidentoffense-report-pd-251",
    sourceLabel: "MPD — Request an Accident Report (PD-10)",
  },
  {
    state: "West Virginia",
    kind: "police-notice",
    trigger: "Injury, death, or total property damage of $1,000 or more.",
    reportTo: "City police inside a municipality; otherwise the county sheriff or nearest West Virginia State Police office",
    deadline: "Immediately",
    formName: null,
    note: "Within 24 hours, the investigating officer must give each party the other drivers' owner, operator and insurance information on request, at no cost.",
    sourceUrl: "https://code.wvlegislature.gov/17C-4-7/",
    sourceLabel: "West Virginia Code § 17C-4-7",
  },
  {
    state: "Wisconsin",
    kind: "driver-report-if-no-police",
    trigger: "Injury or death; $1,000 or more of damage to any one person's property; or $200 or more of damage to government property (other than a government vehicle).",
    reportTo: "Wisconsin Department of Transportation",
    deadline: "Within 10 days",
    formName: "Driver Report of Crash (DT4002)",
    sourceUrl: "https://wisconsindot.gov/Documents/safety/crsh-rpt/dt4002-faq.pdf",
    sourceLabel: "WisDOT — Driver Report of Crash FAQ",
  },
  {
    state: "Wyoming",
    kind: "police-notice",
    trigger: "Injury, death, $1,000 or more of damage to someone else's property, or a vehicle disabled so it can't be driven safely.",
    reportTo: "City police inside a municipality; otherwise the Highway Patrol or county sheriff",
    deadline: "Immediately",
    formName: null,
    sourceUrl: "https://www.dot.state.wy.us/home/dot_safety/crash-reports.html",
    sourceLabel: "WYDOT — Crash Reports",
  },
];

export const KIND_LABEL: Record<ReportKind, string> = {
  "driver-report": "You must file your own report",
  "driver-report-if-no-police": "You file only if police didn't",
  "police-notice": "Call police — no driver form",
  "no-driver-form": "No driver form accepted",
  "uninsured-only": "Only if a driver was uninsured",
  optional: "Optional online report",
  "on-request": "Only if the state asks",
  unconfirmed: "Confirm with your state",
};

export function crashReportingSlug(state: string): string {
  return state.toLowerCase().replace(/,/g, "").replace(/\./g, "").replace(/\s+/g, "-");
}
