import type { Metadata } from "next";
import { LegalPage } from "@/components/layout/legal-page";

export const metadata: Metadata = {
  title: "Legal Disclaimer | FairClaimCalculator",
  description:
    "Legal disclaimer for FairClaimCalculator.com — our tools provide educational claim-audit estimates only and do not constitute legal advice or a professional appraisal.",
};

export default function DisclaimerPage() {
  return (
    <LegalPage title="Legal Disclaimer" lastUpdated="July 2026">
      <div className="rounded-xl border border-accent/30 bg-accent/10 p-5 text-sm leading-relaxed text-foreground">
        <strong>
          Not legal advice. Not a law firm, insurer, or appraisal company. No attorney-client
          relationship.
        </strong>{" "}
        Please read this page in full before using any tool on this site.
      </div>

      <h2>Educational Purpose Only</h2>
      <p>
        FairClaimCalculator.com provides free, self-service tools intended solely for general
        educational and document-organization purposes: checking the facts, comparables, and
        arithmetic behind a diminished-value or total-loss auto insurance offer. Our tools do not
        determine fault or negligence, do not interpret your insurance policy as legal advice, and
        do not predict litigation outcomes.
      </p>

      <h2>The 17c Baseline Is a Comparison Tool, Not &ldquo;True&rdquo; Diminished Value</h2>
      <p>
        Where this site shows a &ldquo;17c insurer-style baseline,&rdquo; that figure comes from a
        formula historically associated with a 2002 Muscogee County, Georgia class-action
        settlement mechanism — not a formula created by the Georgia Supreme Court, and not one
        approved or endorsed by any state insurance regulator as the definitive way to calculate
        diminished value. We show it, with its full arithmetic, purely as one transparent
        comparison point alongside a separate market-evidence worksheet. It is not a professional
        appraisal, and it is not evidence that a specific dollar figure is owed.
      </p>

      <h2>No Legal Advice</h2>
      <p>
        Nothing on this website constitutes legal advice. We are not a law firm, we do not employ
        licensed attorneys to review individual claims submitted through our tools, and no
        content on this site should be relied upon as a substitute for consultation with a
        licensed attorney in your jurisdiction. Laws and regulations governing diminished-value
        claims, total-loss valuation, and claim-settlement practices vary significantly by state
        and change over time; this site does not track or guarantee the currency of
        state-specific legal information referenced in our articles.
      </p>

      <h2>No Attorney-Client Relationship</h2>
      <p>
        Using this website, submitting information to our tools, or contacting us through our
        Contact page does not create an attorney-client relationship between you and
        FairClaimCalculator.com or any individual associated with this site.
      </p>

      <h2>No Guarantee of Outcome</h2>
      <p>
        Outputs produced by our tools are illustrative only. They do not predict, guarantee, or
        represent the amount any insurer will pay, the outcome of any dispute, or the value any
        court, appraiser, or umpire would assign to your vehicle. Insurers, courts, arbitrators,
        and appraisers are not bound by, and may not consider, the output of this or any similar
        online tool.
      </p>

      <h2>Not a Professional Appraisal</h2>
      <p>
        Nothing generated by this site is a certified, court-ready, or professional vehicle
        appraisal unless it is separately prepared and signed by a properly qualified, licensed
        appraiser under a real engagement. Any evidence packet or letter this site helps you
        generate is self-prepared educational material.
      </p>

      <h2>Third-Party Links</h2>
      <p>
        This site may link to third-party resources, including state government or regulator
        pages, valuation-report providers, or professional directories, for informational
        convenience. We do not endorse and are not responsible for the content, accuracy, or
        practices of any linked third-party site.
      </p>

      <h2>Seek Professional Advice</h2>
      <p>
        If your claim involves a material legal dispute, a large loss, a fraud allegation, or a
        filing deadline, we encourage you to consult a licensed attorney in your state or a
        qualified independent auto appraiser before relying on this site&rsquo;s output.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, FairClaimCalculator.com and its operators
        disclaim all liability for any loss or damage arising from reliance on information or
        outputs provided through this website.
      </p>
    </LegalPage>
  );
}
